import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import  Sidebar  from "@/components/sidebar"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gallary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`{inter.className}flex item-start justify-between`}>
        <div className="border-b">
        <div className=" flex h-16 items-centre px-4 py-4">
          <h1 className="text-4xl ">PICTURE GALLERY</h1>
        
        <div className="ml-auto flex items-centre space-x-4"> <Avatar>
  <AvatarImage src="https://github.com/shadcn.png" />
  <AvatarFallback>CN</AvatarFallback>
</Avatar>


        </div>
        </div>
        </div>
        
      
          <div className="flex">
            
              <Sidebar/>
              
            <div className="w-full"> {children}</div>
              
              
            
       </div>
        
    
</body>
</html>
);
}